name: Deployment Status

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Status Update
        env:
          # Mapping your stored secret to an env var
          TARGET_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          echo "Sending notification to endpoint..."
          
          # This sends a JSON package to your URL
          # If the URL is valid, this will return a 200 OK
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Workflow enishaaaaaa completed successfully!"}' \
          $TARGET_URL
